#! IMPORTANT: emptyDir is used for storage — all data is LOST when the Pod restarts.
#! IMPORTANT: Use a PersistentVolumeClaim (PVC) instead of emptyDir for any real data.
#! IMPORTANT: MySQL credentials are hardcoded — use Kubernetes Secrets in production.
# ? StatefulSet gives each Pod a stable identity and ordered deployment/scaling.
# ? Used here for MySQL because it requires a predictable hostname for the headless service DNS.
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: catalog-mysql
  labels:
    app.kubernetes.io/name: catalog
    app.kubernetes.io/instance: catalog
    app.kubernetes.io/component: mysql
    app.kubernetes.io/owner: retail-store-sample
spec:
  replicas: 1
  serviceName: catalog-mysql
  selector:
    matchLabels:
      app.kubernetes.io/name: catalog
      app.kubernetes.io/instance: catalog
      app.kubernetes.io/component: mysql
      app.kubernetes.io/owner: retail-store-sample
  template:
    metadata:
      labels:
        app.kubernetes.io/name: catalog
        app.kubernetes.io/instance: catalog
        app.kubernetes.io/component: mysql
        app.kubernetes.io/owner: retail-store-sample
    spec:
      serviceAccount: catalog-mysql-sa # Service Account    
      containers:
        - name: mysql
          image: "mysql:8.0"
          imagePullPolicy: IfNotPresent
          ports:
            - name: mysql
              containerPort: 3306
              protocol: TCP          
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: my-secret-pw
            - name: MYSQL_DATABASE
              value: catalogdb
          command: ["/bin/bash", "-c"]
          args: # security best practice: avoid hardcoding secrets in env vars; instead, read them from files mounted by the AWS Secrets Store CSI driver and set them as env vars for MySQL at runtime.
            - |
              export MYSQL_USER=$(cat /mnt/secrets-store/MYSQL_USER);
              export MYSQL_PASSWORD=$(cat /mnt/secrets-store/MYSQL_PASSWORD);
              echo "Loaded secrets from AWS Secrets Manager. Starting MySQL with user=$MYSQL_USER";
              exec docker-entrypoint.sh mysqld          
          volumeMounts: # volumeMounts make them available to the container at the specified path; the AWS Secrets Store CSI driver mounts secrets as files in /mnt/secrets-store, which are then read and set as environment variables for MySQL.
            - name: data
              mountPath: /var/lib/mysql
            - name: aws-secrets
              mountPath: /mnt/secrets-store
              readOnly: true              
      volumes: # ? Volumes for MySQL data and AWS Secrets Store CSI driver, bringing secrets from AWS Secrets Manager into the Pod as files.
        - name: data
          emptyDir: {}
        - name: aws-secrets
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "catalog-db-secrets"          
